### ISSUE TITLE
Failed to get a valid session.

### ISSUE THREAD

**Issue by Dr-Murgz** [glomatico/votify#11]
I'm getting the error below:

_votify "https://open.spotify.com/playlist/37i9dQZF1DXe9BSwev1s9f"
[INFO     12:42:59] Starting Votify
[CRITICAL 12:43:01] Failed to get a valid session. Try logging in and exporting your cookies again_

I've just installed it a few hrs ago.

**Comment by glomatico** [comment]
> Try logging in and exporting your cookies again

**Comment by Dr-Murgz** [comment]
Thank you for responding this quick, it is appreciated.

I have tried to export my cookies again using both the chrome and firefox extensions listed. Also logged out and back in and tried exporting my cookies but it's the same error. 

Sample of cookies;
[cookies.txt](https://github.com/user-attachments/files/17474547/cookies.txt)
[spotify.com_cookies.txt](https://github.com/user-attachments/files/17474548/spotify.com_cookies.txt)

**Comment by glomatico** [comment]
Don't post your cookies here, it's a sensitive information.

I'm not sure what the issue is, but you can try using a different browser to export your cookies.

**Comment by Dr-Murgz** [comment]
Hello, the issue is now sorted.
