### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Abhi5033** [glomatico/votify#19]
![image](https://github.com/user-attachments/assets/4d9238fe-a055-4bfb-a81c-2940c491e069)
Updated re-unplayplay but still

**Comment by jaguarondi** [comment]
I have exactly the same error:
re-unplayplay==1.2.6
votify==1.4.4

**Comment by s0llvan** [comment]
Same error
Votify : 1.4.4

**Comment by dgottstein** [comment]
Same error here, Votify 1.4.4...

**Comment by glomatico** [comment]
Duplicate of #5
